apiVersion: v1
kind: Pod
metadata:
  name: securitycontextcontainer-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    securityContext:
      runAsUser: 1001
      capabilities:
            add: ["MAC_ADMIN"]
